apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      run: demo
  replicas: 1
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - name: demo
        image: 192.168.1.190:5000/demo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    run: demo
spec:
  ports:
  - port: 80
  selector:
    run: demo
